//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoMarco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProveedor
    {
        public int idProductos { get; set; }
        public int idProveedor { get; set; }
        public int cantidad { get; set; }
        public int subtotal { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
