//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoMarco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetalleProveedor = new HashSet<DetalleProveedor>();
            this.DetalleVentas = new HashSet<DetalleVentas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public short gradosAlcohol { get; set; }
        public short precio { get; set; }
        public short stock { get; set; }
        public string descripcion { get; set; }
        public int idCategoria { get; set; }
        public string proveedor { get; set; }
        public bool eliminar { get; set; }
        public Nullable<System.DateTime> fechaEliminacion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProveedor> DetalleProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }
    }
}
